# Generated by Django 2.2.12 on 2022-02-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20220220_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='location',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
