# Generated by Django 4.0.3 on 2022-03-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20220225_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('1', 'I do not know now'), ('2', 'Natural Disaster'), ('3', 'Natural Disaster - fires'), ('4', 'Natural Disaster - earthquake'), ('5', 'Natural Disaster - Destruction of Public Property'), ('6', 'Natural Disaster - Pollution'), ('7', 'Crime - Pollution'), ('8', 'Crime - Destruction of Public Property'), ('9', 'Crime - Beating'), ('10', 'Crime - Theft'), ('11', 'Crime')], default='Δεν γνωρίζω', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='dhmos',
            field=models.CharField(choices=[('1', 'Example of Municipality1'), ('2', 'Example Municipality2'), ('3', 'Example of Municipality3'), ('4', 'Example of Municipality4'), ('5', 'Example of Municipality5'), ('6', 'Example of Municipality6'), ('7', 'Example of Municipality7'), ('8', 'Example of Municipality8'), ('9', 'Example of Municipality9'), ('10', 'Example of Municipality 10')], default='Παράδειγμα Δήμου1', max_length=50),
        ),
    ]
